Controllers/BlogController.cs
using AutoMapper;
using CrownBlog.BLL;
using CrownBlog.DAL;
using CrownBlog.Models.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CrownBlog.Filters;

using CrownBlog.Models;
using System.Drawing;

namespace CrownBlog.Controllers
{
    public class BlogController : BaseController
    {
        BlogService BlogService { get; }

        private readonly BlogContext _context;

        private IHttpContextAccessor _httpContextAccessor { get; }


        /// <summary>
        /// AutoMapper
        /// </summary>
        IMapper Mapper { get; }

        IConfiguration _configuration;

        private readonly IServiceProvider _serviceProvider;

        public int totoalNumber;

        [Obsolete]
        public BlogController(BlogContext blogContext,  IConfiguration configuration, IHttpContextAccessor httpContextAccessor, IMapper mapper, IServiceProvider serviceProvider) : base(httpContextAccessor)
        {
            BlogService = new BlogService(blogContext, configuration, null, mapper);
            _context = blogContext;
            _serviceProvider = serviceProvider;
            _configuration = configuration;
            Mapper = mapper;
            _httpContextAccessor = httpContextAccessor;
        }

        public async Task<IActionResult> Index(string searchString, string currentFilter, string keyword, int id, string sortOrder, int? pageNumber, int pageSize = 0)
        {
            ViewData["CurrentSort"] = sortOrder;

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            ViewBag.KeyWord = keyword;
            ViewBag.CurrentPageIndex = pageNumber <= 1 ? 1 : pageNumber;
            ViewBag.TotalPageCount = 1;
            //ViewBag.IndexTranslation = GetResource

            ArticleModel vm = new ArticleModel();
            if (vm == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                vm.ArticleModels = BlogService.GetArticlesByPageFilter(pageNumber, pageSize, searchString);
                //vm.Messages = BlogService.GetMessages();
                //ArticleModel aa = BlogService.GetTags();

                IQueryable<BlogArticle> filterArticles = BlogService.GetFilterArticles(searchString);
                var tmpTotalCount = filterArticles.ToList().Count;

                IQueryable<BlogArticle> allArticles = BlogService.GetAllArticles();

                IQueryable<BlogArticle> topArticles = BlogService.GetTopArticles();

                List<TagItem> tags = BlogService.GetAllTags();
                //var tmpTotalCount = articleModel.ArticleModels.Count;

                if (pageNumber == 0)
                {
                    pageNumber = 1;
                }

                if (pageSize == 0)
                {
                    pageSize = 4;
                }

                PaginatedList<BlogArticle> paginatedList = await PaginatedList<BlogArticle>.CreateAsync(filterArticles, pageNumber ?? 1, pageSize);
                List<ArticleModel> dbArticles = new List<ArticleModel>();

                for (int Idx = 0; Idx < paginatedList.Count; Idx++)
                {
                    dbArticles.Add(new ArticleModel()
                    {
                        Id = paginatedList[Idx].Id,
                        Title = paginatedList[Idx].Title,
                        Description = paginatedList[Idx].Description,
                        BannerUrl = paginatedList[Idx].BannerUrl,
                        Abstract = paginatedList[Idx].Abstract == null ? "" : paginatedList[Idx].Abstract,
                        CreateDate = paginatedList[Idx].CreateDate.GetValueOrDefault(),
                        ModifyDate = paginatedList[Idx].ModifyDate.GetValueOrDefault(),
                        TagName = BlogService.Get_Tags_By(paginatedList[Idx].Id).Select(o => o.Name).FirstOrDefault(),

                    });

                    vm.ArticleModels = dbArticles;
                    List<ArticleModel> totalArticles = BlogService.GetTotalArticles();
                    List<PreNextPageItem> pnPages = new List<PreNextPageItem>();
                    for (int idx = 0; idx < totalArticles.Count; idx++)
                    {
                        PreNextPageItem item = new PreNextPageItem();
                        item.MainArticleId = totalArticles[idx].Id;
                        item.preArticleId = Idx != 0 ? totalArticles[Idx - 1].Id : new Guid();
                        item.preArticleTitle = Idx != 0 ? totalArticles[Idx - 1].Title : string.Empty;
                        item.nextArticleId = Idx < totalArticles.Count - 1 ? totalArticles[Idx + 1].Id : new Guid();
                        item.nextArticleTitle = Idx < totalArticles.Count - 1 ? totalArticles[Idx + 1].Title : string.Empty;
                        pnPages.Add(item);
                    }
                    vm.PNPages = pnPages;
                    vm.Calendars = ConvertDatesToModel(allArticles.ToList());
                    vm.Years = allArticles.Select(o => o.CreateDate.Value.Year).Distinct().ToList();
                    vm.Tags = tags;
                    vm.TopArticles = ConvertArticleEntitiesToModels(topArticles.ToList());

                    List<BlogTag> blogTags = BlogService.GetAllTagsBy(paginatedList[Idx].Id);
                    List<TagItem> displayTags = new List<TagItem>();

                    foreach (var exitTagItem in blogTags)
                    {
                        displayTags.Add(new TagItem
                        {
                            Name = exitTagItem.Name,
                            TagId = exitTagItem.TagId,
                            ArticleId = exitTagItem.ArticleId,
                            Description = exitTagItem.Description,
                            Status = exitTagItem.Status
                        });
                    }

                    vm.TagSelectedItem = displayTags;
                }

                ViewBag.TotalPageCount = (tmpTotalCount / pageSize) + (tmpTotalCount % pageSize == 0 ? 0 : 1);

                return View(vm);
            }
        }

        public IActionResult Details(Guid id = new Guid(), Guid pId = new Guid(), Guid nId = new Guid())
        {
            ArticleModel vm = BlogService.GetArticleById(id, pId, nId);
            if (vm == null || id == Guid.Empty)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.articleId = Guid.Parse(id.ToString());
                ViewBag.preArticleId = Guid.Parse(pId.ToString());
                ViewBag.nextArticleId = Guid.Parse(nId.ToString());

                //Article Tags
                List<BlogTag> blogTags = BlogService.GetAllTagsBy(id);
                List<string> tagNames = blogTags.Select(o => o.Name).ToList();
                vm.SelectedTags = tagNames;

                List<BlogMessage> blogMessages = BlogService.Get_All_Messages_By(id);
                List<MessageItem> messageModels = new List<MessageItem>();
                foreach (var item in blogMessages)
                {
                    if (item.MessageId != Guid.Empty)
                    {
                        var messageMode = Mapper.Map<MessageItem>(item);
                        messageModels.Add(messageMode);
                    }
                }
                vm.Messages = messageModels;

                #region SideBar
                IQueryable<BlogArticle> allArticles = BlogService.GetAllArticles();
                vm.Years = allArticles.Select(o => o.CreateDate.Value.Year).Distinct().ToList();
                vm.Calendars = ConvertDatesToModel(allArticles.ToList());

                List<TagItem> tags = BlogService.GetAllTags();
                vm.Tags = tags;
                #endregion

                return View(vm);
            }
        }

        [TypeFilter(typeof(AuthFilter))]
        public IActionResult Create()
        {
            ArticleModel vm = new ArticleModel();

            List<TagItem> tags = BlogService.GetAllTags();
            vm.Tags = tags;

            //string token = "exampleToken";
            //Response.Cookies.Append("CrownAuth", token, new CookieOptions() { HttpOnly = true, Expires = DateTime.Now.AddYears(100) });


            return View(vm);
        }

        [TypeFilter(typeof(AuthFilter))]
        public async Task<IActionResult> Edit(Guid Id)
        {
            ViewBag.articleId = Id;
            if (Id == Guid.Empty)
            {
                return NotFound();
            }

            ArticleModel vm = await BlogService.GetArticleByIdAsync(Id);

            if (vm == null)
            {
                return NotFound();
            }

            //Right Nav Tags
            List<TagItem> tags = BlogService.GetAllTags();
            vm.Tags = tags;

            //Article Tags
            List<BlogTag> blogTags = BlogService.GetAllTagsBy(Id);
            List<string> tagNames = blogTags.Select(o => o.Name).ToList();
            vm.SelectedTags = tagNames;


            return View(vm);
        }

        public async Task<IActionResult> Category(string categoryName, int? pageNumber, int year = 0, int month = 0, string pageIndex = "1", int pageSize = 6)
        {
            ArticleModel vm = new ArticleModel();

            List<BlogArticle> allArticles = BlogService.GetAllArticles().ToList();
            List<BlogArticle> articles = new List<BlogArticle>();

            List<ArticleModel> cateogyrArticles = new List<ArticleModel>();

ViewComponents/PaginationViewComponent.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace CrownBlog.ViewComponents
{
    public class PaginationViewComponent : ViewComponent
    {
        protected readonly IHostingEnvironment Env;
        protected readonly CrownBlog.DAL.BlogContext blogContext;

        public PaginationViewComponent(IHostingEnvironment env, CrownBlog.DAL.BlogContext _blogContext)
        {
            Env = env;
            blogContext = _blogContext;
        }

        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

Views/Blog/Album.cshtml
@model CrownBlog.Models.ViewModel.PhotoAlbumModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutBlog.cshtml";
}

@section Css{
    <link rel="stylesheet" href="~/css/color-box/colorbox.css" />
}


@section HeaderScripts{
    <script type="text/javascript" src="~/js/color-box/jquery.colorbox.js"></script>
}

<partial name="../Shared/_Header.cshtml" />

<main id="main" class="site-main">
    <partial name="../Shared/_Banner.cshtml" />

    <div class="album py-5 bg-light">
        <div class="container">

            <div class="row">
                @if (Model.AlbumList != null && Model.AlbumList.Count > 0)
                {
                    @foreach (var item in Model.AlbumList)
                    {
                        <div class="col-md-4">
                            <div class="card mb-4 box-shadow">
                                <img class="card-img-top"
                                     data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" 
                                     alt="Thumbnail [100%x225]" style="height: 225px; width: 100%; display: block;"
                                     src="@item.GalleryUrl" />
                                <div class="card-body">
                                    <p class="card-text">@item.Title</p>
                                    <div class="d-flex justify-content-between align-items-center">
                                        <div class="btn-group">
                                            <a href="/blog/album/details/@ViewBag.albumId?albumTitle=@item.Title.Replace("&", "and")">
                                                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                                            </a>
                                            <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                                        </div>
                                        <small class="text-muted">9 mins</small>
                                    </div>
                                </div>
                            </div>
                        </div>

                    }
                }
            </div>
        </div>
    </div>

</main>

Views/Blog/AlbumDetails.cshtml
@model CrownBlog.Models.ViewModel.PhotoAlbumModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutBlog.cshtml";
}

@section Css{
    <link rel="stylesheet" href="~/css/color-box/colorbox.css" />
}


@section HeaderScripts{
    <script type="text/javascript" src="~/js/color-box/jquery.colorbox.js"></script>
}

@section Scripts{
    <script>
        $(".photo-item").colorbox({
            maxWidth: '970px',
            maxHeight: '95%',
            rel: 'gallery-item'
        })
    </script>
}

<partial name="../Shared/_Header.cshtml" />


<main id="main" class="site-main">
    <partial name="../Shared/_Banner.cshtml" />
    <div class="album py-5 bg-light">
        <div class="container">
            <h1>@Model.Title</h1>

            <div class="row">
                @if (Model.Gallerys != null && Model.Gallerys.Count > 0)
                {
                    foreach (var item in Model.Gallerys)
                    {
                        <div class="col-md-3">
                            <div class="card mb-4 box-shadow">
                                <a class="photo-item" href=@item.ImgUrl alt="">
                                    <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" alt="Thumbnail [100%x225]" style="height: 225px; width: 100%; display: block;"
                                         src=@item.ThumbImgUrl data-holder-rendered="true">
                                </a>
                                <div class="card-body">
                                    <p class="card-text">@item.Title</p>
                                </div>
                            </div>
                        </div>
                    }
                }

            </div>
        </div>
    </div>

</main>

Views/Blog/Category.cshtml
@model CrownBlog.Models.ViewModel.ArticleModel
@{
    ViewBag.Title = "Category";
    Layout = "~/Views/Shared/_LayoutBlog.cshtml";
}

@section Css{
    <style>

        .card-img {
            height: 350px;
        }
    </style>
}

@section Scripts{
    <script type="text/javascript">
        $(function () {
            var totalPage = parseInt(@ViewBag.TotalNum);
            totalPage = Math.round(totalPage / 6);
            if (@ViewBag.TotalNum % 6 !==0) {
                totalPage += 1;
            }

            var currentIndex = getUrlParameter('pageIndex') || 1;
            var pageOptions = { pageTotal: totalPage, curPage: parseInt(currentIndex), paginationId: '' };
            dynamicPagingFunc(pageOptions);

            function getUrlParameter(name) {
                name = name.replace(/[\[]/, '\\[').replace(/[\]]/, '\\]');
                var regex = new RegExp('[\\?&]' + name + '=([^&#]*)');
                var results = regex.exec(location.search);
                return results === null ? '' : decodeURIComponent(results[1].replace(/\+/g, ' '));
            };

            function dynamicPagingFunc(pageOptions) {
                var pageTotal = pageOptions.pageTotal || 1;
                var curPage = pageOptions.curPage || 1;
                var doc = document;
                var paginationId = doc.getElementById('' + pageOptions.paginationId + '') || doc.getElementById('pagination');
                var html = '';
                if (curPage > pageTotal) {
                    curPage = 1;
                }
                /*總頁數小於6，全部顯示*/
                if (pageTotal <= 6) {
                    html = appendItem(pageTotal, curPage, html);
                    paginationId.innerHTML = html;
                }
                /*總頁數大於6時，要分析當前頁*/
                if (pageTotal > 6) {
                    if (curPage <= 4) {
                        html = appendItem(pageTotal, curPage, html);
                        paginationId.innerHTML = html;
                    } else if (curPage > 4) {
                        html = appendItem(pageTotal, curPage, html);
                        paginationId.innerHTML = html;
                    }
                }
            }

            function appendItem(pageTotal, curPage, html) {
                var starPage = 0;
                var endPage = 0;

                var ltClass = curPage === 1 ? 'pagination nopage' : 'pagination';
                var rtClass = pageTotal === curPage ? 'rtbn nopage' : 'rtbn';

                //html += "<dt class='" + ltClass + "'> <a href='/blog/category?pageIndex=" + (parseInt(curPage - 1)) + "'></a></dt>";
                //html += "<ul class='" + ltClass + "'> <a href='/blog/category?pageIndex=" + (parseInt(curPage - 1)) + "'></a></ul>";

                if (pageTotal <= 6) {
                    starPage = 1;
                    endPage = pageTotal;
                } else if (pageTotal > 6 && curPage <= 5) {
                    starPage = 1;
                    endPage = 6;
                    if (curPage == 5) {
                        endPage = 6;
                    }
                } else {
                    if (pageTotal == curPage) {
                        starPage = (parseInt(curPage - 5));
                        endPage = (parseInt(curPage));
                    } else {
                        starPage = (parseInt(curPage - 3));
                        endPage = (parseInt(curPage + 1));
                    }

                    //html += "<ul class><a id='first' class='page-link' href='/blog/category?pageIndex=1'>1</a><dd class='more-page'>...</ul></ul>";
                }

                for (let i = starPage; i <= endPage; i++) {
                    if (i == curPage) {
                        html += '<li class="page-item active"><a id="first" class="page-link" href="/blog/category?pageIndex=' + i + '">' + i + '</a></li>';
                    } else {
                        html += '<li class="page-item"><a class="page-link" href="/blog/category?pageIndex=' + i + '">' + i + '</a></li>';
                    }
                }

                if (curPage < (parseInt(pageTotal) - 2)) {
                    html += '<li class="page-item more-page">...</li>';
                }
                if (curPage <= (parseInt(pageTotal) - 2)) {
                    html += '<li class="page-item"><a class="page-link" href="/blog/category?pageIndex=' + pageTotal + '">' + pageTotal + '</a></li>';
                }

                //if (pageTotal <= 6) {
                //    html += '<ul class="' + rtClass +'"><a  class="page-link" href="/blog/category?pageIndex=' + (parseInt(currentIndex) + 1) + '"></a></ul>';
                //} else {
                //    if (curPage < (parseInt(pageTotal) - 2)) {
                //        html += '<li class="page-item more-page">...</li>';
                //    }
                //    if (curPage <= (parseInt(pageTotal) - 2)) {
                //        html += '<li class="page-item"><a class="page-link" href="/blog/category?pageIndex=' + pageTotal + '">' + pageTotal + '</a></li>';
                //    }
                //    //html += '<ul class="' + rtClass +'"><a class="page-link" href="/blog/category?pageIndex=' + (parseInt(currentIndex) + 1) + '"></a></ul>';
                //}
                return html;
            }
        });
    </script>
}


<partial name="../Shared/_Header.cshtml" />

<!--================ Hero sm Banner start =================-->
<partial name="../Shared/_Banner.cshtml" />
<!--================ Hero sm Banner end =================-->
<!--================ Start Blog Post Area =================-->
<section id="cateogyrSection" class="blog-post-area section-margin">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="row">
                    @if(Model.ArticleModels != null && Model.ArticleModels.Count > 0){

                        foreach (var item in Model.ArticleModels)
                    {
                    <div class="col-md-6">
                        <div class="single-recent-blog-post card-view">
                            <div class="thumb">
                                <img class="card-img rounded-0" src=@item.BannerUrl alt="">
                                <ul class="thumb-info">
                                    <li><a href="#"><i class="ti-user"></i>Admin</a></li>
                                    <li><a href="#"><i class="ti-themify-favicon"></i>@item.CommentCount  Comments</a></li>
                                </ul>
                            </div>
                            <div class="details mt-20">
                                <a href="blog-single.html">
                                    <h3>
                                        @item.Title
                                    </h3>
                                </a>
                                <p>@item.Abstract</p>
                                <a class="button" href="/blog/details/@item.Id">Read More <i class="ti-arrow-right"></i></a>
                            </div>
                        </div>
                    </div>
                    }
                    }



                </div>

                <nav class="blog-pagination justify-content-center d-flex">
                    <ul id="pagination" class="page pagination"></ul>
                </nav>
            </div>

            <!-- Start Blog Post Siddebar -->
            <div class="col-lg-4 sidebar-widgets">
                <div class="widget-wrap">
                    <partial name="../Tuple/_SearchBar.cshtml" />

                    @if (Model.Calendars != null && Model.Calendars.Count > 0)
                    {
                        @*@Html.Partial("../Tuple/_SidebarCalendar", Model)*@
                        @await Html.PartialAsync("../Tuple/_SidebarCalendar", Model)
                    }

                    @if (Model.Tags != null && Model.Tags.Count > 0)
                    {
                        @*@Html.Partial("../Tuple/_SidebarTag", Model.Tags)*@
                        @await Html.PartialAsync("../Tuple/_SidebarTag", Model)
                    }

                </div>
            </div>
            <!-- End Blog Post Siddebar -->
        </div>
</section>
<!--================ End Blog Post Area =================-->

Views/Blog/Contact.cshtml
@{
    ViewBag.Title = "Contact";
    Layout = "~/Views/Shared/_LayoutBlog.cshtml";

}

<partial name="../Shared/_Header.cshtml" />

<main id="main" class="site-main">
    <partial name="../Shared/_Banner.cshtml" />

    <section>
        <div class="container">

            <h2>@ViewBag.Title.</h2>
            <h3>@ViewBag.Message</h3>

            <address>
                One Microsoft Way<br />
                Redmond, WA 98052-6399<br />
                <abbr title="Phone">P:</abbr>
                425.555.0100
            </address>

            <address>
                <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
                <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
            </address>
        </div>
    </section>
</main>

Views/Blog/Index.cshtml
@model CrownBlog.Models.ViewModel.ArticleModel;

@using CrownBlog.BLL;
@using System
@using System.Collections.Generic
@using System.Globalization

@{
    ViewData["PageTitle"] = "Blog List";

    Layout = "~/Views/Shared/_LayoutBlog.cshtml";
}


<partial name="../Shared/_Header.cshtml" />

<main id="main" class="site-main">
    <!--================Hero Banner start =================-->
    <partial name="../Shared/_Banner.cshtml" />
    <!--================Hero Banner end =================-->
    <!--================ Blog slider start =================-->
    <section>
        <div class="container">
            <div class="owl-carousel owl-theme blog-slider">
                @if(Model.TopArticles != null && Model.TopArticles.Count >= 0)
                {
                    @foreach (var topItem in Model.TopArticles)
                    {
                        <div class="card blog__slide text-center">
                            <div class="blog__slide__img">
                                <img class="card-img rounded-0" src="@topItem.BannerUrl" alt="">
                            </div>
                            <div class="blog__slide__content">
                                <a class="blog__slide__label" href="/blog/details/@topItem.Id">Memory</a>
                                <h3>

                                    @if (Model.PNPages != null && Model.PNPages.Count > 0)
                                    {
                                        <a href="/blog/details/@topItem.Id?pId=@Model.PNPages.Where(o => o.MainArticleId == topItem.Id).Select(o => o.preArticleId)&nId=@Model.PNPages.Where(o => o.MainArticleId == topItem.Id).Select(o => o.nextArticleId)">@topItem.Title</a>
                                    }
                                    else
                                    {
                                        <a href="/blog/details/@topItem.Id?">@topItem.Title</a>
                                    }
                                </h3>

                                <p>@topItem.Abstract</p>
                            </div>
                        </div>
                    }
                }
            </div>
        </div>
    </section>
    <!--================ Blog slider end =================-->
    <!--================ Start Blog Post Area =================-->
    <section class="blog-post-area section-margin mt-4">
        <div class="container">
            <div class="row">
                <div id="main-article-area" class="col-lg-8">

                    @foreach (var item in Model.ArticleModels)
                    {

                        <div class="single-recent-blog-post">
                            <div class="thumb">
                                <img class="img-fluid" width="730" height="389" src=@item.BannerUrl alt="">
                                <ul class="thumb-info">
                                    <li><a href="#"><i class="ti-user"></i>Andy.Chung</a></li>
                                    <li><a href="#"><i class="ti-notepad"></i>@item.CreateDate.Value.ToString("MMM dd, yyyy", CultureInfo.CreateSpecificCulture("en-GB"))</a></li>
                                    <li><a href="#"><i class="ti-themify-favicon"></i>@item.CommentCount Comments</a></li>
                                </ul>

                            </div>
                            <div class="details mt-20">
                                <a href="/blog/details/@item.Id">
                                    <h3>
                                        @Html.DisplayFor(modelItem => item.Title)
                                    </h3>
                                </a>
                                @if (item.TagName != null)
                                {

                                    <p class="tag-list-inline">
                                        Tag:
                                        @if (Model.TagSelectedItem != null && Model.TagSelectedItem.Count >= 0)
                                        {
                                            @for (var i = 0; i < Model.TagSelectedItem.Count; i++)
                                            {
                                                @if (i == Model.TagSelectedItem.Count - 1)
                                                {
                                                    <a href="/blog/category?categoryName=@Model.TagSelectedItem[i].Name">@Model.TagSelectedItem[i].Name</a>

                                                }
                                                else
                                                {
                                                    <a href="/blog/category?categoryName=@Model.TagSelectedItem[i].Name">@Model.TagSelectedItem[i].Name,</a>

                                                }
                                            }
                                        }

                                    </p>
                                }
                                <p>@item.Abstract</p>
                                @if (Model.PNPages != null && Model.PNPages.Count > 0)
                                {
                                    //if(){

                                    //}
                                    <a class="button" href="/blog/details/@item.Id?pId=@Model.PNPages.Where(o => o.MainArticleId == item.Id).Select(o => o.preArticleId).First()&nId=@Model.PNPages.Where(o => o.MainArticleId == item.Id).Select(o => o.nextArticleId).First()">Read More <i class="ti-arrow-right"></i></a>
                                }
                                else
                                {
                                    <a class="button" href="/blog/details/@item.Id">Read More <i class="ti-arrow-right"></i></a>
                                }
                            </div>
                        </div>


                    }
                    <div class="row">
                        <div class="col-lg-12">

                            @await Component.InvokeAsync("Pagination")

                        </div>
                    </div>

                </div>

                <!-- Start Blog Post Siddebar -->
                <div class="col-lg-4 sidebar-widgets">
                    <div class="widget-wrap">


                        <partial name="../Tuple/_SearchBar.cshtml" />

                        @if (Model.Calendars != null && Model.Calendars.Count > 0)
                        {
                            @*@Html.Partial("../Tuple/_SidebarCalendar", Model)*@
                            @await Html.PartialAsync("../Tuple/_SidebarCalendar", Model)
                        }

                        @if (Model.Tags != null && Model.Tags.Count > 0)
                        {
                            @*@Html.Partial("../Tuple/_SidebarTag", Model.Tags)*@
                            @await Html.PartialAsync("../Tuple/_SidebarTag", Model)
                        }
                    </div>
                </div>
            </div>
            <!-- End Blog Post Siddebar -->
        </div>
    </section>
    <!--================ End Blog Post Area =================-->
</main>